name: Setup Poetry env
description: Set up Python, install Poetry, and install project dependencies.

inputs:
  python-version:
    description: Python version to set up.
    required: false
    default: "3.11"

runs:
  using: composite
  steps:
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
    - name: Install Poetry
      shell: bash
      run: pip install poetry
    - name: Install dependencies
      shell: bash
      run: poetry install --no-interaction
